name: build-push-deploy

on:
  workflow_dispatch:

jobs:
  Trigger_Gateway_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Call
        run: |
          http_response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s -o /dev/null -w "%{http_code}" \
          https://api.github.com/repos/kukrejaravi9/TestRepo/actions/workflows/deploy-to-production.yml/dispatches \
          -d '{"ref":"main","inputs":{"AZURE_REPOSITORY": "Hello"}}') \
          && if [ $http_response != "204" ]; then \
              exit 1 \ 
          fi \
