name: build-push-deploy

on:
  workflow_dispatch:

#jobs:
  #slack_update_building:
    #uses: kukrejaravi9/TestRepo/.github/workflows/deploy-to-production.yml@main
    #secrets: inherit

jobs:
  create_image_tag:
    runs-on: ubuntu-latest   
    steps: 
      - name: Set image tag
        id: set_image_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: |
          http_response=$(curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -s -o /dev/null -w "%{http_code}" \
          https://api.github.com/repos/kukrejaravi9/TestRepo/actions/workflows/deploy-to-production.yml/dispatches \
          -d '{"ref":"main"}') \
          && if [ $http_response != "204" ]; then \
              exit 1 \ 
          fi \        
        
