name: Build, Push, and Deploy to Azure
on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string
        description: Skaffold Image Name(i.e. utils)

jobs:
  create_image_tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile_environment: ['dev', 'test', 'prod']
      max-parallel: 1
    environment: ${{ matrix.profile_environment }}
    steps: 
      - name: Set image tag
        id: set_image_tag
        run: echo ${{ inputs.ENV_NAME }}
